name = "IrosRegistry"
uuid = "ffee7c97-fb58-4e81-b8a5-ed8cf42b8dbc"
repo = "https://github.com/wrs28/IrosRegistry.git"
description = "For Iros.jl"

[packages]
# fede57cc-428a-11e9-3e5c-c149a0a4072d = { name = "ArnoldiMethodTransformations", path = "ArnoldiMethodTransformations"}
573aa7f4-91c9-40a8-9c96-241bf90c799c = { name = "Iris", path = "Iris"}
