name = "IrosRegistry"
uuid = "ffee7c97-fb58-4e81-b8a5-ed8cf42b8dbc"
repo = "https://github.com/wrs28/IrosRegistry.git"
description = "For Iros.jl"

[packages]
fede57cc-428a-11e9-3e5c-c149a0a4072d = { name = "ArnoldiMethodWrapper", path = "ArnoldiMethodWrapper"}
573aa7f4-91c9-40a8-9c96-241bf90c799c = { name = "Iros", path = "Iros"}
dc165baa-4ec7-4ba6-9649-6ad7c8c72a04 = { name = "IrosBase", path = "IrosBase" }
e66d2882-6afb-11e9-2ba9-e36c7c16e84e = { name = "IrosDefaults", path = "IrosDefaults"}
b2ce5262-62bd-11e9-037d-a93ccda198f7 = { name = "IrosSpectral", path = "IrosSpectral"}
8158958c-316f-11e9-3ff7-338d4f1f622e = { name = "MUMPS3", path = "MUMPS3"}
